# Generated by Django 3.0.3 on 2020-02-19 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gw_practicum', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='zip',
            field=models.IntegerField(),
        ),
    ]
