# Generated by Django 3.0.3 on 2020-02-20 21:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gw_practicum', '0004_auto_20200219_2059'),
    ]

    operations = [
        migrations.CreateModel(
            name='PracticumDirector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gw_practicum.Department')),
                ('user_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PracticumPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('competencies', models.TextField()),
                ('l_obj1', models.TextField()),
                ('l_obj2', models.TextField(null=True)),
                ('l_obj3', models.TextField(null=True)),
                ('l_obj4', models.TextField(null=True)),
                ('l_obj5', models.TextField(null=True)),
                ('request_on', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True)),
                ('agreement', models.BooleanField()),
                ('preceptor_approval', models.BooleanField()),
                ('pd_approval', models.BooleanField()),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gw_practicum.Department')),
                ('practicum_director', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gw_practicum.PracticumDirector')),
                ('preceptor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gw_practicum.Preceptor')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gw_practicum.Site')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gw_practicum.Student')),
            ],
        ),
        migrations.CreateModel(
            name='StudentSelfEvaluation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orientation', models.IntegerField(choices=[(1, 'Excellent'), (2, 'Good'), (3, 'Poor'), (4, 'Bad')])),
                ('achievement', models.IntegerField(choices=[(1, 'Excellent'), (2, 'Good'), (3, 'Poor'), (4, 'Bad')])),
                ('communication', models.IntegerField(choices=[(1, 'Excellent'), (2, 'Good'), (3, 'Poor'), (4, 'Bad')])),
                ('feedback', models.IntegerField(choices=[(1, 'Excellent'), (2, 'Good'), (3, 'Poor'), (4, 'Bad')])),
                ('discussion', models.IntegerField(choices=[(1, 'Excellent'), (2, 'Good'), (3, 'Poor'), (4, 'Bad')])),
                ('l_objects', models.TextField()),
                ('request_on', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gw_practicum.Department')),
                ('practicum_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gw_practicum.PracticumPlan')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gw_practicum.Site')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gw_practicum.Student')),
            ],
        ),
        migrations.CreateModel(
            name='PreceptorFinalEvaluation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reliable', models.IntegerField(choices=[(1, 'Excellent'), (2, 'Good'), (3, 'Poor'), (4, 'Bad')])),
                ('behavior', models.IntegerField(choices=[(1, 'Excellent'), (2, 'Good'), (3, 'Poor'), (4, 'Bad')])),
                ('initiative', models.IntegerField(choices=[(1, 'Excellent'), (2, 'Good'), (3, 'Poor'), (4, 'Bad')])),
                ('independent_work', models.IntegerField(choices=[(1, 'Excellent'), (2, 'Good'), (3, 'Poor'), (4, 'Bad')])),
                ('projects', models.IntegerField(choices=[(1, 'Excellent'), (2, 'Good'), (3, 'Poor'), (4, 'Bad')])),
                ('overall_work', models.TextField()),
                ('pd_approval', models.BooleanField()),
                ('request_on', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gw_practicum.Department')),
                ('practicum_director', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gw_practicum.PracticumDirector')),
                ('practicum_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gw_practicum.PracticumPlan')),
                ('preceptor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gw_practicum.Preceptor')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gw_practicum.Site')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gw_practicum.Student')),
            ],
        ),
        migrations.CreateModel(
            name='MidpointEvaluation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competencies', models.TextField()),
                ('l_obj1', models.TextField()),
                ('l_activities1', models.TextField()),
                ('l_activities2', models.TextField(null=True)),
                ('l_activities3', models.TextField(null=True)),
                ('l_activities4', models.TextField(null=True)),
                ('l_activities5', models.TextField(null=True)),
                ('agreement', models.BooleanField()),
                ('request_on', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True)),
                ('preceptor_approval', models.BooleanField()),
                ('pd_approval', models.BooleanField()),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gw_practicum.Department')),
                ('practicum_director', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gw_practicum.PracticumDirector')),
                ('practicum_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gw_practicum.PracticumPlan')),
                ('preceptor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gw_practicum.Preceptor')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gw_practicum.Site')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gw_practicum.Student')),
            ],
        ),
    ]
