# Generated by Django 3.0.3 on 2020-02-24 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gw_practicum', '0006_remove_preceptor_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='preceptor',
            name='site',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gw_practicum.Site'),
        ),
    ]
