# Generated by Django 3.0.3 on 2020-02-24 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gw_practicum', '0007_preceptor_site'),
    ]

    operations = [
        migrations.AlterField(
            model_name='practicumplan',
            name='pd_approval',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='practicumplan',
            name='preceptor_approval',
            field=models.BooleanField(null=True),
        ),
    ]
