# Generated by Django 3.0.3 on 2020-02-27 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gw_practicum', '0008_auto_20200224_1841'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hours',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('hours', models.DecimalField(decimal_places=1, max_digits=3)),
                ('tasks', models.TextField()),
                ('practicum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gw_practicum.PracticumPlan')),
            ],
        ),
    ]
