# Generated by Django 3.0.3 on 2020-02-28 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gw_practicum', '0011_auto_20200227_1702'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hours',
            name='student',
        ),
    ]
