# Generated by Django 3.0.3 on 2020-02-28 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gw_practicum', '0012_remove_hours_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='hours',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gw_practicum.Student'),
        ),
    ]
