# Generated by Django 3.0.3 on 2020-02-28 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gw_practicum', '0013_hours_student'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hours',
            old_name='practicum',
            new_name='practicum_id',
        ),
        migrations.RenameField(
            model_name='hours',
            old_name='student',
            new_name='student_id',
        ),
    ]
