# Generated by Django 3.0.3 on 2020-02-28 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gw_practicum', '0015_auto_20200228_1944'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hours',
            old_name='practicum_id',
            new_name='practicum',
        ),
        migrations.RenameField(
            model_name='hours',
            old_name='student_id',
            new_name='student',
        ),
    ]
